import {
  CANONICAL_TERMINAL_DEAL_STAGE_SLUGS,
  LOST_DEAL_STAGE_SLUGS,
  WON_DEAL_STAGE_SLUGS,
} from "@trock-crm/shared/types";

export const TERMINAL_STAGE_SLUGS = [
  ...new Set([...CANONICAL_TERMINAL_DEAL_STAGE_SLUGS, ...WON_DEAL_STAGE_SLUGS, ...LOST_DEAL_STAGE_SLUGS]),
] as readonly string[];

export const WON_STAGE_SLUGS = WON_DEAL_STAGE_SLUGS;
export const LOST_STAGE_SLUGS = LOST_DEAL_STAGE_SLUGS;
