import { describe, expect, it } from "vitest";
import { buildDealStageSummary, buildLeadStageSummary } from "./pipeline-stage-summary";
import type { DealStagePageResponse } from "@/hooks/use-deals";
import type { LeadStagePageResponse } from "@/hooks/use-leads";

const now = new Date("2026-04-22T12:00:00.000Z");

describe("buildDealStageSummary", () => {
  it("derives count, stage value, and average visible age", () => {
    const data: DealStagePageResponse = {
      stage: { id: "stage-est", name: "Estimating", slug: "estimating" },
      scope: "team",
      summary: { count: 3, totalValue: 245000, averageDaysInStage: 3 },
      pagination: { page: 1, pageSize: 25, total: 3, totalPages: 1 },
      rows: [
        {
          id: "deal-1",
          dealNumber: "TR-1001",
          name: "North Tower",
          stageId: "stage-est",
          pipelineDisposition: "deals",
          workflowRoute: "normal",
          isBidBoardOwned: false,
          bidBoardStageSlug: null,
          readOnlySyncedAt: null,
          assignedRepId: "rep-1",
          companyId: null,
          propertyId: null,
          sourceLeadId: null,
          primaryContactId: null,
          ddEstimate: "245000",
          bidEstimate: null,
          awardedAmount: null,
          changeOrderTotal: null,
          description: null,
          propertyAddress: null,
          propertyCity: "Dallas",
          propertyState: "TX",
          propertyZip: null,
          projectTypeId: null,
          regionId: null,
          source: null,
          winProbability: null,
          decisionMakerName: null,
          decisionProcess: null,
          budgetStatus: null,
          incumbentVendor: null,
          unitCount: null,
          buildYear: null,
          forecastWindow: null,
          forecastCategory: null,
          forecastConfidencePercent: null,
          forecastRevenue: null,
          forecastGrossProfit: null,
          forecastBlockers: null,
          nextStep: null,
          nextStepDueAt: null,
          nextMilestoneAt: null,
          supportNeededType: null,
          supportNeededNotes: null,
          forecastUpdatedAt: null,
          forecastUpdatedBy: null,
          procoreProjectId: null,
          procoreBidId: null,
          procoreLastSyncedAt: null,
          lostReasonId: null,
          lostNotes: null,
          lostCompetitor: null,
          lostAt: null,
          expectedCloseDate: null,
          actualCloseDate: null,
          lastActivityAt: null,
          stageEnteredAt: "2026-04-18T12:00:00.000Z",
          isActive: true,
          hubspotDealId: null,
          createdAt: "2026-04-18T12:00:00.000Z",
          updatedAt: "2026-04-18T12:00:00.000Z",
        },
        {
          id: "deal-2",
          dealNumber: "TR-1002",
          name: "Victory Park",
          stageId: "stage-est",
          pipelineDisposition: "deals",
          workflowRoute: "normal",
          isBidBoardOwned: false,
          bidBoardStageSlug: null,
          readOnlySyncedAt: null,
          assignedRepId: "rep-1",
          companyId: null,
          propertyId: null,
          sourceLeadId: null,
          primaryContactId: null,
          ddEstimate: "100000",
          bidEstimate: null,
          awardedAmount: null,
          changeOrderTotal: null,
          description: null,
          propertyAddress: null,
          propertyCity: "Austin",
          propertyState: "TX",
          propertyZip: null,
          projectTypeId: null,
          regionId: null,
          source: null,
          winProbability: null,
          decisionMakerName: null,
          decisionProcess: null,
          budgetStatus: null,
          incumbentVendor: null,
          unitCount: null,
          buildYear: null,
          forecastWindow: null,
          forecastCategory: null,
          forecastConfidencePercent: null,
          forecastRevenue: null,
          forecastGrossProfit: null,
          forecastBlockers: null,
          nextStep: null,
          nextStepDueAt: null,
          nextMilestoneAt: null,
          supportNeededType: null,
          supportNeededNotes: null,
          forecastUpdatedAt: null,
          forecastUpdatedBy: null,
          procoreProjectId: null,
          procoreBidId: null,
          procoreLastSyncedAt: null,
          lostReasonId: null,
          lostNotes: null,
          lostCompetitor: null,
          lostAt: null,
          expectedCloseDate: null,
          actualCloseDate: null,
          lastActivityAt: null,
          stageEnteredAt: "2026-04-20T12:00:00.000Z",
          isActive: true,
          hubspotDealId: null,
          createdAt: "2026-04-20T12:00:00.000Z",
          updatedAt: "2026-04-20T12:00:00.000Z",
        },
      ],
    };

    expect(buildDealStageSummary(data, now)).toEqual({
      totalCount: 3,
      totalValue: 245000,
      averageAgeDays: 3,
    });
  });
});

describe("buildLeadStageSummary", () => {
  it("derives count, average visible age, and qualified/opportunity context", () => {
    const data: LeadStagePageResponse = {
      stage: {
        id: "stage-opportunity",
        name: "Qualified for Opportunity",
        slug: "qualified_for_opportunity",
      },
      scope: "mine",
      summary: { count: 2 },
      pagination: { page: 1, pageSize: 25, total: 2, totalPages: 1 },
      rows: [
        {
          id: "lead-1",
          name: "Acme Facility",
          stageId: "stage-opportunity",
          stageEnteredAt: "2026-04-18T12:00:00.000Z",
          updatedAt: "2026-04-18T12:00:00.000Z",
          companyName: "Acme",
          source: "Referral",
        },
        {
          id: "lead-2",
          name: "North Campus",
          stageId: "stage-opportunity",
          stageEnteredAt: "2026-04-20T12:00:00.000Z",
          updatedAt: "2026-04-20T12:00:00.000Z",
          companyName: "North Campus",
          source: "Web",
        },
      ],
    };

    expect(buildLeadStageSummary(data, now)).toEqual({
      totalCount: 2,
      averageAgeDays: 3,
      isQualifiedPressureStage: true,
      isOpportunityStage: true,
    });
  });
});
