export {
  BID_BOARD_MIRRORED_STAGE_SLUGS,
  CANONICAL_DEAL_STAGE_LABELS,
  CANONICAL_DEAL_STAGE_SLUGS,
  CRM_OWNED_LEAD_STAGE_LABELS,
  CRM_OWNED_LEAD_STAGE_SLUGS,
  NORMAL_DEAL_STAGE_SLUGS,
  SALES_WORKFLOW,
  SALES_WORKFLOW_DISQUALIFICATION_REASONS,
  SALES_WORKFLOW_PIPELINE_TYPES,
  SERVICE_DEAL_STAGE_SLUGS,
} from "@trock-crm/shared/types";
