FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
ENV NODE_ENV=development
RUN npm ci
RUN npm run build --workspace=shared
RUN npm run build --workspace=client

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/client/dist ./dist
EXPOSE 3000
CMD ["serve", "dist", "-s", "-l", "3000"]
