FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
ENV NODE_ENV=development
ARG VITE_API_BASE_URL
ARG VITE_API_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_API_URL=${VITE_API_URL}
RUN npm ci
RUN npm run build --workspace=shared
RUN npm run build --workspace=client-field

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve

COPY --from=builder /app/client-field/dist ./dist

EXPOSE 3000
CMD ["serve", "dist", "-s", "-l", "3000"]
