FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
ENV NODE_ENV=development
RUN npm ci
RUN npm run build --workspace=shared
RUN npm run build --workspace=worker

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app .
ENV NODE_ENV=production
CMD ["node", "worker/dist/index.js"]
