import { describe, expect, it } from "vitest";
import { normalizeDealBoardResponse } from "./use-deals";

describe("normalizeDealBoardResponse", () => {
  it("maps server pipeline columns with `deals` arrays into board columns with `cards`", () => {
    const result = normalizeDealBoardResponse({
      pipelineColumns: [
        {
          stage: { id: "stage-1", name: "Open", slug: "open" },
          count: 1,
          totalValue: 5000,
          deals: [
            {
              id: "deal-1",
              dealNumber: "D-1",
              name: "Example Deal",
              stageId: "stage-1",
              pipelineDisposition: "deals",
              workflowRoute: "estimating",
              assignedRepId: "rep-1",
              companyId: null,
              propertyId: null,
              sourceLeadId: null,
              primaryContactId: null,
              ddEstimate: null,
              bidEstimate: "5000",
              awardedAmount: null,
              changeOrderTotal: null,
              description: null,
              propertyAddress: null,
              propertyCity: null,
              propertyState: null,
              propertyZip: null,
              projectTypeId: null,
              regionId: null,
              source: null,
              winProbability: null,
              decisionMakerName: null,
              decisionProcess: null,
              budgetStatus: null,
              incumbentVendor: null,
              unitCount: null,
              buildYear: null,
              forecastWindow: null,
              forecastCategory: null,
              forecastConfidencePercent: null,
              forecastRevenue: null,
              forecastGrossProfit: null,
              forecastBlockers: null,
              nextStep: null,
              nextStepDueAt: null,
              nextMilestoneAt: null,
              supportNeededType: null,
              supportNeededNotes: null,
              forecastUpdatedAt: null,
              forecastUpdatedBy: null,
              procoreProjectId: null,
              procoreBidId: null,
              procoreLastSyncedAt: null,
              lostReasonId: null,
              lostNotes: null,
              lostCompetitor: null,
              lostAt: null,
              expectedCloseDate: null,
              actualCloseDate: null,
              lastActivityAt: null,
              stageEnteredAt: "2026-04-21T00:00:00.000Z",
              isActive: true,
              hubspotDealId: null,
              createdAt: "2026-04-21T00:00:00.000Z",
              updatedAt: "2026-04-21T00:00:00.000Z",
            },
          ],
        },
      ],
      columns: [
        {
          stage: { id: "stage-1", name: "Open", slug: "open" },
          count: 1,
          totalValue: 5000,
          deals: [
            {
              id: "deal-1",
              dealNumber: "D-1",
              name: "Example Deal",
              stageId: "stage-1",
              pipelineDisposition: "deals",
              workflowRoute: "estimating",
              assignedRepId: "rep-1",
              companyId: null,
              propertyId: null,
              sourceLeadId: null,
              primaryContactId: null,
              ddEstimate: null,
              bidEstimate: "5000",
              awardedAmount: null,
              changeOrderTotal: null,
              description: null,
              propertyAddress: null,
              propertyCity: null,
              propertyState: null,
              propertyZip: null,
              projectTypeId: null,
              regionId: null,
              source: null,
              winProbability: null,
              decisionMakerName: null,
              decisionProcess: null,
              budgetStatus: null,
              incumbentVendor: null,
              unitCount: null,
              buildYear: null,
              forecastWindow: null,
              forecastCategory: null,
              forecastConfidencePercent: null,
              forecastRevenue: null,
              forecastGrossProfit: null,
              forecastBlockers: null,
              nextStep: null,
              nextStepDueAt: null,
              nextMilestoneAt: null,
              supportNeededType: null,
              supportNeededNotes: null,
              forecastUpdatedAt: null,
              forecastUpdatedBy: null,
              procoreProjectId: null,
              procoreBidId: null,
              procoreLastSyncedAt: null,
              lostReasonId: null,
              lostNotes: null,
              lostCompetitor: null,
              lostAt: null,
              expectedCloseDate: null,
              actualCloseDate: null,
              lastActivityAt: null,
              stageEnteredAt: "2026-04-21T00:00:00.000Z",
              isActive: true,
              hubspotDealId: null,
              createdAt: "2026-04-21T00:00:00.000Z",
              updatedAt: "2026-04-21T00:00:00.000Z",
            },
          ],
        },
      ],
      terminalStages: [],
    });

    expect(result.columns[0].cards).toHaveLength(1);
    expect(result.columns[0].cards[0].id).toBe("deal-1");
  });
});
