import { describe, expect, it } from "vitest";
import { buildSalesReviewOverview } from "../../../src/modules/sales-review/service.js";

describe("sales review service", () => {
  it("builds forecast, activity cadence, hygiene, and support views from canonical records", () => {
    const overview = buildSalesReviewOverview({
      actor: { role: "director", userId: "director-1" },
      filters: { from: "2026-04-01", to: "2026-04-20" },
      leads: [
        {
          id: "lead-1",
          companyId: "company-1",
          propertyId: "property-1",
          primaryContactId: null,
          name: "Lead One",
          stageId: "qualified_lead",
          assignedRepId: "rep-1",
          status: "open",
          source: "Referral",
          description: null,
          decisionMakerName: null,
          decisionProcess: null,
          budgetStatus: null,
          incumbentVendor: null,
          unitCount: null,
          buildYear: null,
          forecastWindow: "30_days",
          forecastCategory: "commit",
          forecastConfidencePercent: 85,
          forecastRevenue: "250000.00",
          forecastGrossProfit: "40000.00",
          forecastBlockers: "Waiting on owner sign-off",
          nextStep: "Owner review call",
          nextStepDueAt: null,
          nextMilestoneAt: new Date("2026-04-22T00:00:00.000Z"),
          supportNeededType: "leadership",
          supportNeededNotes: null,
          forecastUpdatedAt: null,
          forecastUpdatedBy: null,
          lastActivityAt: new Date("2026-04-19T00:00:00.000Z"),
          stageEnteredAt: new Date("2026-04-10T00:00:00.000Z"),
          convertedAt: null,
          isActive: true,
          createdAt: new Date("2026-04-15T00:00:00.000Z"),
          updatedAt: new Date("2026-04-19T00:00:00.000Z"),
        },
      ],
      deals: [
        {
          id: "deal-1",
          dealNumber: "TR-2026-0001",
          name: "Deal One",
          stageId: "estimating",
          assignedRepId: "rep-1",
          primaryContactId: null,
          companyId: "company-1",
          propertyId: "property-1",
          sourceLeadId: "lead-1",
          ddEstimate: null,
          bidEstimate: null,
          awardedAmount: null,
          changeOrderTotal: "0",
          description: null,
          propertyAddress: null,
          propertyCity: null,
          propertyState: null,
          propertyZip: null,
          projectTypeId: null,
          regionId: null,
          source: "Referral",
          winProbability: null,
          decisionMakerName: null,
          decisionProcess: null,
          budgetStatus: null,
          incumbentVendor: null,
          unitCount: null,
          buildYear: null,
          forecastWindow: "60_days",
          forecastCategory: "best_case",
          forecastConfidencePercent: 55,
          forecastRevenue: "500000.00",
          forecastGrossProfit: null,
          forecastBlockers: null,
          nextStep: null,
          nextStepDueAt: null,
          nextMilestoneAt: null,
          supportNeededType: null,
          supportNeededNotes: null,
          forecastUpdatedAt: null,
          forecastUpdatedBy: null,
          procoreProjectId: null,
          procoreBidId: null,
          procoreLastSyncedAt: null,
          lostReasonId: null,
          lostNotes: null,
          lostCompetitor: null,
          lostAt: null,
          expectedCloseDate: null,
          actualCloseDate: null,
          workflowRoute: "estimating",
          lastActivityAt: new Date("2026-04-01T00:00:00.000Z"),
          stageEnteredAt: new Date("2026-04-01T00:00:00.000Z"),
          isActive: true,
          hubspotDealId: null,
          companycamProjectId: null,
          propertyLat: null,
          propertyLng: null,
          estimatingSubstage: null,
          proposalStatus: "not_started",
          proposalSentAt: null,
          proposalAcceptedAt: null,
          proposalRevisionCount: 0,
          proposalNotes: null,
          createdAt: new Date("2026-04-05T00:00:00.000Z"),
          updatedAt: new Date("2026-04-01T00:00:00.000Z"),
        },
      ],
      activities: [
        {
          id: "activity-1",
          type: "call",
          responsibleUserId: "rep-1",
          performedByUserId: "rep-1",
          sourceEntityType: "lead",
          sourceEntityId: "lead-1",
          companyId: "company-1",
          propertyId: "property-1",
          leadId: "lead-1",
          dealId: null,
          contactId: null,
          emailId: null,
          subject: null,
          body: null,
          outcome: null,
          nextStep: null,
          nextStepDueAt: null,
          durationMinutes: null,
          occurredAt: new Date("2026-04-18T00:00:00.000Z"),
          createdAt: new Date("2026-04-18T00:00:00.000Z"),
        },
      ],
      users: [{ id: "rep-1", displayName: "Caleb Rep" }],
      companies: [{ id: "company-1", name: "Asset Living" }],
      properties: [{ id: "property-1", name: "Palm Villas" }],
    });

    expect(overview.newOpportunities).toHaveLength(2);
    expect(overview.forecast).toHaveLength(2);
    expect(overview.activityCadence[0]?.calls7d).toBe(1);
    expect(overview.supportRequests).toHaveLength(1);
    expect(overview.hygiene[0]?.id).toBe("deal-1");
  });
});
