import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import {
  getMondayShowcaseData,
  getMondayShowcaseEvidence,
  type MondayShowcaseData,
} from "../../../src/modules/reports/monday-showcase-service.js";
import type { WorkflowRouteBucket } from "../../../src/modules/shared/deal-value-sql.js";
import { SENT_STAGE_SLUGS, ESTIMATED_STAGE_SLUGS } from "../../../src/modules/reports/foundations.js";
import { WON_STAGE_SLUGS } from "../../../src/modules/shared/pipeline-terminal-stages.js";

/**
 * REAL-SQL guarantees for the Monday-showcase Service / Other filter (PGlite in-memory Postgres).
 *
 * This suite drives the TOP-LEVEL functions the route handlers call -- getMondayShowcaseData for the
 * payload all 8 variants slice, and getMondayShowcaseEvidence for the drill -- deliberately NOT the SQL
 * builders underneath. The property that matters to a reader of this report is "the card said 6 and the
 * drawer opened 6", and only the top-level pair can assert that. Three things are locked here:
 *
 *   1. RECONCILIATION -- for EVERY filter state (both / service / other), every headline figure equals the
 *      number of records its own evidence query returns. This is the defect class this repo has shipped
 *      repeatedly: a card and its drill-through computed by predicates that drift apart.
 *   2. ADDITIVITY -- service-only + other-only === both-selected, figure by figure. A total partition
 *      cannot lose a row; if this fails, either the predicate is not total or the source is unfilterable.
 *   3. DEFAULT INERTNESS -- the both-buckets payload is deep-equal to the no-filter-at-all payload. A
 *      weekly report must not move a single number because a filter shipped.
 *
 * The one documented exception is Active leads: the `leads` table has no workflow_route, so that figure is
 * NOT additive (it repeats in full under both buckets). That is asserted POSITIVELY below rather than
 * skipped -- a silently-omitted case is how an unfilterable source stops being noticed.
 */

// Valid v4-shaped UUIDs (12-hex final group) generated by padding, so seed ids never go malformed.
const U = (s: string) => `00000000-0000-0000-0000-${s.padStart(12, "0")}`;
const REP_A = U("a01");
const REP_B = U("b01");
const ST = {
  won: U("57001"),
  open: U("57002"),
  sent: U("57003"),
  estimating: U("57004"),
  leadNew: U("57005"),
};
const D = {
  w1: U("11001"), w2: U("11002"), w3: U("11003"), w4: U("11004"), w5: U("11005"), w6: U("11006"),
  s1: U("21001"), s2: U("21002"), s3: U("21003"), e1: U("21005"), e2: U("21006"),
  p1: U("31001"), p2: U("31002"), p3: U("31003"), p4: U("31004"), p5: U("31005"), p6: U("31006"), p7: U("31007"),
  l1: U("41001"), l2: U("41002"), l3: U("41003"),
};

// Fixed clock for the Won/Sent/Estimated window. Projection is a snapshot metric anchored on the REAL CT
// today (the same now() the band CASE uses), so those rows are seeded relative to now() instead.
const NOW = new Date("2026-05-27T18:00:00Z");

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let tdb: any;
let pg: PGlite;

beforeAll(async () => {
  pg = new PGlite();
  await pg.exec(`
    CREATE TABLE users (id uuid PRIMARY KEY, display_name text NOT NULL);
    CREATE TABLE pipeline_stage_config (
      id uuid PRIMARY KEY, name text NOT NULL, slug text UNIQUE NOT NULL,
      workflow_family text NOT NULL DEFAULT 'standard_deal', is_terminal boolean NOT NULL DEFAULT false
    );
    -- workflow_route is deliberately declared NULLABLE TEXT here, while production has it NOT NULL enum
    -- defaulting to 'normal'. That is the ONLY way to exercise the null leg of the Other bucket, which is
    -- the guard that keeps the partition total if a nullable route ever appears (a new import path, a
    -- legacy row). Without a null row in this fixture the additivity assertions below could not tell a
    -- correct predicate from a bare not-equals, which silently drops nulls from BOTH buckets.
    CREATE TABLE deals (
      id uuid PRIMARY KEY, sales_source_user_id uuid, deal_number text, project_number text, name text NOT NULL, stage_id uuid NOT NULL,
      assigned_rep_id uuid, is_test_data boolean NOT NULL DEFAULT false, is_change_order boolean NOT NULL DEFAULT false, on_hold boolean NOT NULL DEFAULT false,
      is_active boolean NOT NULL DEFAULT true, won_closed_date date, expected_close_date date, bid_due_date timestamptz, bid_board_stage_slug text,
      dd_estimate numeric, bid_estimate numeric, awarded_amount numeric, bid_board_total_sales numeric,
      company_id uuid, region_id uuid, project_type text, project_type_id uuid, stage_entered_at timestamptz,
      win_probability integer, workflow_route text
    );
    CREATE TABLE deal_stage_history (
      id uuid PRIMARY KEY DEFAULT gen_random_uuid(), deal_id uuid NOT NULL, to_stage_id uuid NOT NULL,
      created_at timestamptz NOT NULL
    );
    CREATE TABLE leads (
      id uuid PRIMARY KEY, name text NOT NULL, stage_id uuid NOT NULL, assigned_rep_id uuid,
      status text NOT NULL DEFAULT 'open', is_active boolean NOT NULL DEFAULT true,
      is_test_data boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(),
      company_id uuid, project_type text, project_type_id uuid, stage_entered_at timestamptz
    );
    CREATE TABLE companies (id uuid PRIMARY KEY, name text NOT NULL, region text);
    CREATE TABLE region_config (id uuid PRIMARY KEY, name text NOT NULL);
    CREATE TABLE project_type_config (id uuid PRIMARY KEY, name text NOT NULL);

    INSERT INTO users (id, display_name) VALUES ('${REP_A}', 'Alice Rep'), ('${REP_B}', 'Bob Rep');

    INSERT INTO pipeline_stage_config (id, name, slug, workflow_family, is_terminal) VALUES
      ('${ST.won}',        'Won',           '${WON_STAGE_SLUGS[0]}',      'standard_deal', true),
      ('${ST.open}',       'Opportunity',   'opportunity',                'standard_deal', false),
      ('${ST.sent}',       'Estimate Sent', '${SENT_STAGE_SLUGS[0]}',     'standard_deal', false),
      ('${ST.estimating}', 'Estimating',    '${ESTIMATED_STAGE_SLUGS[0]}','standard_deal', false),
      ('${ST.leadNew}',    'New',           'lead_new',                   'lead', false);

    -- ===== WON: mixed routes, incl. a NULL-route row that must land in Other. =====
    INSERT INTO deals (id, deal_number, name, stage_id, assigned_rep_id, won_closed_date, awarded_amount, is_test_data, on_hold, workflow_route) VALUES
      ('${D.w1}','W-1','Won service A','${ST.won}','${REP_A}','2026-05-25', 100000, false, false, 'service'),
      ('${D.w2}','W-2','Won normal B','${ST.won}','${REP_B}','2026-05-26', 200000, false, false, 'normal'),
      ('${D.w3}','W-3','Won null-route unassigned','${ST.won}',NULL,'2026-05-25', 50000, false, false, NULL),
      ('${D.w4}','W-4','Won onhold (excl)','${ST.won}','${REP_A}','2026-05-25', 999, false, true, 'service'),
      ('${D.w5}','W-5','Won test (excl)','${ST.won}','${REP_A}','2026-05-25', 888, true, false, 'service'),
      ('${D.w6}','W-6','Won out-of-window (excl)','${ST.won}','${REP_A}','2026-05-20', 777, false, false, 'service');

    -- ===== SENT / ESTIMATED: stage-entry cohorts, mixed routes (s1 enters twice -> still ONE deal). =====
    INSERT INTO deals (id, deal_number, name, stage_id, assigned_rep_id, bid_board_total_sales, on_hold, is_test_data, workflow_route) VALUES
      ('${D.s1}','S-1','Sent service A','${ST.open}','${REP_A}', 30000, false, false, 'service'),
      ('${D.s2}','S-2','Sent normal B','${ST.open}','${REP_B}', 45000, false, false, 'normal'),
      ('${D.s3}','S-3','Sent null-route A','${ST.open}','${REP_A}', 25000, false, false, NULL),
      ('${D.e1}','E-1','Est service A','${ST.open}','${REP_A}', 60000, false, false, 'service'),
      ('${D.e2}','E-2','Est normal B','${ST.open}','${REP_B}', 70000, false, false, 'normal');
    INSERT INTO deal_stage_history (deal_id, to_stage_id, created_at) VALUES
      ('${D.s1}','${ST.sent}','2026-05-25T15:00:00Z'),
      ('${D.s1}','${ST.sent}','2026-05-26T15:00:00Z'),
      ('${D.s2}','${ST.sent}','2026-05-26T16:00:00Z'),
      ('${D.s3}','${ST.sent}','2026-05-26T16:30:00Z'),
      ('${D.e1}','${ST.estimating}','2026-05-25T17:00:00Z'),
      ('${D.e2}','${ST.estimating}','2026-05-26T17:00:00Z');

    -- ===== PROJECTION: open + future-dated relative to CT today; plus the M-only blind spots. =====
    INSERT INTO deals (id, deal_number, name, stage_id, assigned_rep_id, expected_close_date, bid_board_total_sales, is_active, on_hold, is_test_data, workflow_route) VALUES
      ('${D.p1}','P-1','Proj service 0_30','${ST.open}','${REP_A}', (now() AT TIME ZONE 'America/Chicago')::date + 10, 30000, true, false, false, 'service'),
      ('${D.p2}','P-2','Proj normal 31_60','${ST.open}','${REP_A}', (now() AT TIME ZONE 'America/Chicago')::date + 45, 40000, true, false, false, 'normal'),
      ('${D.p3}','P-3','Proj service 0_30 B','${ST.open}','${REP_B}', (now() AT TIME ZONE 'America/Chicago')::date + 20, 20000, true, false, false, 'service'),
      ('${D.p4}','P-4','Proj normal no-date','${ST.open}','${REP_A}', NULL, 15000, true, false, false, 'normal'),
      ('${D.p5}','P-5','Proj service stale','${ST.open}','${REP_A}', (now() AT TIME ZONE 'America/Chicago')::date - 5, 12000, true, false, false, 'service'),
      ('${D.p6}','P-6','Proj onhold (excl)','${ST.open}','${REP_A}', (now() AT TIME ZONE 'America/Chicago')::date + 10, 13000, true, true, false, 'service'),
      ('${D.p7}','P-7','Proj null-route 0_30','${ST.open}','${REP_B}', (now() AT TIME ZONE 'America/Chicago')::date + 5, 18000, true, false, false, NULL);

    -- ===== LEADS: no workflow_route column exists at all -- these are the unfilterable figure. =====
    INSERT INTO leads (id, name, stage_id, assigned_rep_id, status, is_active, is_test_data) VALUES
      ('${D.l1}','Lead A','${ST.leadNew}','${REP_A}','open', true, false),
      ('${D.l2}','Lead B','${ST.leadNew}','${REP_B}','open', true, false),
      ('${D.l3}','Lead A2','${ST.leadNew}','${REP_A}','open', true, false);
  `);

  tdb = drizzle(pg);
});

afterAll(async () => {
  await pg?.close?.();
});

const BOTH: WorkflowRouteBucket[] = ["service", "other"];
const SERVICE: WorkflowRouteBucket[] = ["service"];
const OTHER: WorkflowRouteBucket[] = ["other"];

function showcase(routes?: readonly WorkflowRouteBucket[]): Promise<MondayShowcaseData> {
  return getMondayShowcaseData(tdb, { mode: "to_date", now: NOW, routes });
}

/** The evidence COUNT for one metric/scope under one selection -- what the drawer would show. */
async function evidenceCount(
  metric: Parameters<typeof getMondayShowcaseEvidence>[1]["metric"],
  routes: readonly WorkflowRouteBucket[] | undefined,
  extra: Partial<Parameters<typeof getMondayShowcaseEvidence>[1]> = {}
): Promise<number> {
  const ev = await getMondayShowcaseEvidence(tdb, { metric, mode: "to_date", now: NOW, routes, ...extra });
  return ev.total.count;
}

/**
 * Every headline figure in the payload, reduced to a comparable count. This ONE list is what both the
 * reconciliation and the additivity suites iterate, so a figure can never be filtered-and-tested in one
 * and forgotten in the other. `evidence` describes the drill the number links to.
 */
function figures(data: MondayShowcaseData) {
  const dept = (key: string) => data.departments.find((d) => d.key === key)!;
  return [
    { name: "execHero.won", count: data.execHero.won.count, evidence: { metric: "won" as const } },
    { name: "execHero.sent", count: data.execHero.sent.count, evidence: { metric: "sent" as const } },
    { name: "execHero.estimated", count: data.execHero.estimated.count, evidence: { metric: "estimated" as const } },
    { name: "departments.won", count: dept("won").count ?? -1, evidence: { metric: "won" as const } },
    { name: "departments.sent", count: dept("sent").count ?? -1, evidence: { metric: "sent" as const } },
    { name: "departments.estimating", count: dept("estimating").count ?? -1, evidence: { metric: "estimated" as const } },
    {
      name: "officeProjection.bands(total)",
      count: data.officeProjection.bands.reduce((s, b) => s + b.count, 0),
      evidence: { metric: "projection" as const },
    },
    ...data.officeProjection.bands.map((b) => ({
      name: `officeProjection.band.${b.band}`,
      count: b.count,
      evidence: { metric: "projection" as const, band: b.band },
    })),
    {
      name: "officeProjection.undated(M-N)",
      count: data.officeProjection.coverage.m - data.officeProjection.coverage.n,
      evidence: { metric: "undated" as const },
    },
    {
      name: "officeProjection.blindSpots.stale",
      count: data.officeProjection.blindSpots?.stale.count ?? -1,
      evidence: { metric: "stale" as const },
    },
    {
      name: "officeProjection.blindSpots.noDate",
      count: data.officeProjection.blindSpots?.noDate.count ?? -1,
      evidence: { metric: "no_date" as const },
    },
  ];
}

/** The office lead total, exactly as the B2 footer computes it (Σ every rep bucket incl. Unassigned). */
function leadTotal(data: MondayShowcaseData): number {
  return data.reps.reduce((s, r) => s + r.leadStatus.reduce((t, l) => t + l.count, 0), 0);
}

describe("card count === drilled record count, under EVERY filter state", () => {
  it.each([
    ["both (default)", undefined],
    ["both (explicit)", BOTH],
    ["service only", SERVICE],
    ["other only", OTHER],
  ] as const)("%s", async (_label, routes) => {
    const data = await showcase(routes);
    for (const fig of figures(data)) {
      const drilled = await evidenceCount(fig.evidence.metric, routes, fig.evidence);
      expect(`${fig.name}=${fig.count}`).toBe(`${fig.name}=${drilled}`);
    }
    // Leads too: unfilterable, but the badge and its drill must STILL agree with each other -- that is
    // what makes "unfiltered" honest rather than broken.
    expect(leadTotal(data)).toBe(await evidenceCount("leads", routes));
  });

  it("reconciles per REP as well as office-wide (the B2/B3 row drills)", async () => {
    for (const routes of [BOTH, SERVICE, OTHER]) {
      const data = await showcase(routes);
      expect(data.reps.length).toBeGreaterThan(0);
      for (const rep of data.reps) {
        expect(rep.closed.count).toBe(await evidenceCount("won", routes, { repId: rep.repId }));
        expect(rep.sentThisWeek.count).toBe(await evidenceCount("sent", routes, { repId: rep.repId }));
      }
    }
  });

  it("reconciles $ as well as counts, for the money figures", async () => {
    for (const routes of [BOTH, SERVICE, OTHER]) {
      const data = await showcase(routes);
      const won = await getMondayShowcaseEvidence(tdb, { metric: "won", mode: "to_date", now: NOW, routes });
      expect(won.total.value ?? 0).toBeCloseTo(data.execHero.won.value.amount, 2);
      const sent = await getMondayShowcaseEvidence(tdb, { metric: "sent", mode: "to_date", now: NOW, routes });
      expect(sent.total.value ?? 0).toBeCloseTo(data.execHero.sent.value.amount, 2);
    }
  });
});

describe("additivity: service-only + other-only === both-selected", () => {
  it("holds for every deal-sourced figure", async () => {
    const both = figures(await showcase(BOTH));
    const service = figures(await showcase(SERVICE));
    const other = figures(await showcase(OTHER));
    expect(both).toHaveLength(service.length);
    for (let i = 0; i < both.length; i++) {
      // Name the figure inside the compared strings so a failure says WHICH figure lost rows, not just
      // "expected 5 to be 6" from an anonymous loop.
      expect(`${both[i].name}: service+other=${service[i].count + other[i].count}`).toBe(
        `${both[i].name}: service+other=${both[i].count}`
      );
    }
  });

  it("holds for the Won and Sent $ totals, not just their counts", async () => {
    const both = await showcase(BOTH);
    const service = await showcase(SERVICE);
    const other = await showcase(OTHER);
    expect(service.execHero.won.value.amount + other.execHero.won.value.amount).toBeCloseTo(
      both.execHero.won.value.amount,
      2
    );
    expect(service.execHero.sent.value.amount + other.execHero.sent.value.amount).toBeCloseTo(
      both.execHero.sent.value.amount,
      2
    );
  });

  it("is NON-TRIVIAL: each bucket is a real, strictly smaller slice of a non-zero whole", async () => {
    const both = await showcase(BOTH);
    const service = await showcase(SERVICE);
    const other = await showcase(OTHER);
    // Without these guards every additivity assertion above would pass vacuously on 0 + 0 === 0.
    expect(both.execHero.won.count).toBe(3);
    expect(service.execHero.won.count).toBe(1);
    expect(other.execHero.won.count).toBe(2);
    expect(both.execHero.sent.count).toBe(3);
    expect(service.execHero.sent.count).toBe(1);
    expect(other.execHero.sent.count).toBe(2);
    const bands = (d: MondayShowcaseData) => d.officeProjection.bands.reduce((s, b) => s + b.count, 0);
    expect(bands(both)).toBe(4);
    expect(bands(service)).toBe(2);
    expect(bands(other)).toBe(2);
  });

  it("does NOT hold for Active leads -- the ONE unfilterable figure, asserted rather than skipped", async () => {
    const both = leadTotal(await showcase(BOTH));
    const service = leadTotal(await showcase(SERVICE));
    const other = leadTotal(await showcase(OTHER));
    expect(both).toBe(3); // non-trivial
    // The leads table has no workflow_route: each bucket returns the FULL set, so the buckets sum to
    // double. This is the documented behaviour, not a bug -- and the payload says so out loud below.
    expect(service).toBe(both);
    expect(other).toBe(both);
    expect(service + other).not.toBe(both);
  });
});

describe("a NULL workflow_route counts as Other", () => {
  it("puts the null-route Won deal in Other and never in Service", async () => {
    const service = await getMondayShowcaseEvidence(tdb, { metric: "won", mode: "to_date", now: NOW, routes: SERVICE });
    const other = await getMondayShowcaseEvidence(tdb, { metric: "won", mode: "to_date", now: NOW, routes: OTHER });
    const names = (ev: { records: Array<{ name: string }> }) => ev.records.map((r) => r.name);
    expect(names(other)).toContain("Won null-route unassigned");
    expect(names(service)).not.toContain("Won null-route unassigned");
  });

  it("puts null-route deals in Other for the Sent cohort and the projection snapshot too", async () => {
    const sentOther = await getMondayShowcaseEvidence(tdb, { metric: "sent", mode: "to_date", now: NOW, routes: OTHER });
    expect(sentOther.records.map((r) => r.name)).toContain("Sent null-route A");
    const projOther = await getMondayShowcaseEvidence(tdb, { metric: "projection", mode: "to_date", now: NOW, routes: OTHER });
    expect(projOther.records.map((r) => r.name)).toContain("Proj null-route 0_30");
  });
});

describe("the default state is inert", () => {
  it("both-buckets returns a payload deep-equal to passing no filter at all", async () => {
    expect(await showcase(BOTH)).toEqual(await showcase(undefined));
  });

  it("bucket ORDER does not change the payload", async () => {
    expect(await showcase(["other", "service"])).toEqual(await showcase(BOTH));
  });

  it("describes itself as inactive, with nothing disclaimed", async () => {
    const data = await showcase(undefined);
    expect(data.routeFilter).toEqual({ selected: ["service", "other"], active: false, unfilterable: [] });
    // No route caveat is appended to the source notes when nothing is narrowed.
    expect(data.notes.some((note) => note.includes("Filtered to"))).toBe(false);
  });
});

describe("the payload names what the filter could not reach", () => {
  it("flags the unfilterable figures when (and only when) the selection narrows", async () => {
    const data = await showcase(SERVICE);
    expect(data.routeFilter.active).toBe(true);
    expect(data.routeFilter.selected).toEqual(["service"]);
    expect(data.routeFilter.unfilterable.join(" ")).toMatch(/Active leads/);
    expect(data.routeFilter.unfilterable.join(" ")).toMatch(/Collected/);
    expect(data.notes.some((note) => note.includes("Filtered to Service only"))).toBe(true);
  });

  it("keeps the routeFilter field and the source notes describing the SAME state", async () => {
    // The notes are the mechanism that discloses "Active leads are not route-filtered". If the payload
    // could declare one filter state while its own notes described another, that disclosure would be
    // unreliable exactly when it matters. Both are derived from ONE resolved descriptor; this pins that.
    for (const routes of [undefined, BOTH, SERVICE, OTHER]) {
      const data = await showcase(routes);
      const notesClaimNarrowing = data.notes.some((note) => note.includes("Filtered to"));
      expect(`routes=${routes ?? "absent"} notesNarrow=${notesClaimNarrowing}`).toBe(
        `routes=${routes ?? "absent"} notesNarrow=${data.routeFilter.active}`
      );
      if (data.routeFilter.active) {
        // The note names the SAME bucket the field carries, and repeats the same unfilterable list.
        // Matched on the bucket WORD, not the full label ("Other (non-service)"), so the copy can be
        // reworded without this becoming a wording test -- what is pinned is that they agree.
        const bucketWord = data.routeFilter.selected[0] === "service" ? "Service" : "Other";
        expect(data.notes.some((note) => note.includes(`Filtered to ${bucketWord}`))).toBe(true);
        const otherWord = bucketWord === "Service" ? "Other" : "Service";
        expect(data.notes.some((note) => note.includes(`Filtered to ${otherWord}`))).toBe(false);
        for (const figure of data.routeFilter.unfilterable) {
          expect(data.notes.some((note) => note.includes(figure))).toBe(true);
        }
      }
    }
  });

  it("marks the leads DRILL as not-applied while every deal drill is applied", async () => {
    const leads = await getMondayShowcaseEvidence(tdb, { metric: "leads", mode: "to_date", now: NOW, routes: SERVICE });
    expect(leads.routeFilter).toEqual({ selected: ["service"], active: true, applied: false });
    for (const metric of ["won", "sent", "estimated", "projection", "undated", "stale", "no_date"] as const) {
      const ev = await getMondayShowcaseEvidence(tdb, { metric, mode: "to_date", now: NOW, routes: SERVICE });
      expect(`${metric}.applied=${ev.routeFilter.applied}`).toBe(`${metric}.applied=true`);
    }
  });

  it("reports applied=false for every metric when the selection does not narrow", async () => {
    const ev = await getMondayShowcaseEvidence(tdb, { metric: "won", mode: "to_date", now: NOW, routes: BOTH });
    expect(ev.routeFilter).toEqual({ selected: ["service", "other"], active: false, applied: false });
  });
});

describe("an empty selection has no payload", () => {
  it("throws rather than returning a full or zeroed report", async () => {
    await expect(showcase([])).rejects.toThrow(/at least one/i);
    await expect(
      getMondayShowcaseEvidence(tdb, { metric: "won", mode: "to_date", now: NOW, routes: [] })
    ).rejects.toThrow(/at least one/i);
  });
});
