import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import type { SQL } from "drizzle-orm";
import {
  getWonCloseSummary,
  getCanonicalRepWonSummary,
} from "../../../src/modules/dashboard/service.js";
import {
  buildStageEntryCohortSql,
  buildProjectionBandsSql,
  buildProjectionCoverageSql,
  buildLeadStatusSql,
  buildWonEvidenceSql,
  buildStageEntryEvidenceSql,
  buildProjectionEvidenceSql,
  buildUndatedEvidenceSql,
  buildLeadEvidenceSql,
} from "../../../src/modules/reports/monday-showcase-service.js";
import { SENT_STAGE_SLUGS, ESTIMATED_STAGE_SLUGS, type ProjectionBand } from "../../../src/modules/reports/foundations.js";
import { WON_STAGE_SLUGS } from "../../../src/modules/shared/pipeline-terminal-stages.js";
import { getWtdPeriod } from "../../../src/lib/period.js";

/**
 * REAL-SQL reconciliation (PGlite in-memory Postgres) for Reports Part 3 drill-to-evidence.
 *
 * The headline guarantee: the RECORDS behind a showcase number are EXACTLY the set that number
 * aggregates. We seed one prod-shaped dataset and, for EVERY metric/scope, assert the evidence
 * row-select reconciles to the SAME aggregate the showcase renders -- Won against the REAL protected
 * getWonCloseSummary / getCanonicalRepWonSummary, Sent/Estimated/Projection/Leads against the showcase's
 * own aggregate builders. Mocks were the gap that let "looks reconciled" ship; this runs the actual SQL.
 */

// Valid v4-shaped UUIDs (12-hex final group) generated by padding, so seed ids never go malformed.
const U = (s: string) => `00000000-0000-0000-0000-${s.padStart(12, "0")}`;
const REP_A = U("a01");
const REP_B = U("b01");
const ST = {
  won: U("57001"),
  open: U("57002"),
  sent: U("57003"),
  estimating: U("57004"),
  leadNew: U("57005"),
  leadContacted: U("57006"),
};
const D = {
  w1: U("11001"), w2: U("11002"), w3: U("11003"), w4: U("11004"), w5: U("11005"), w6: U("11006"),
  s1: U("21001"), s2: U("21002"), s3: U("21003"), s4: U("21004"), e1: U("21005"), e2: U("21006"),
  p1: U("31001"), p2: U("31002"), p3: U("31003"), p4: U("31004"), p5: U("31005"), p6: U("31006"),
  l1: U("41001"), l2: U("41002"), l3: U("41003"), l4: U("41004"), l5: U("41005"), l6: U("41006"),
};

// to_date week for a deterministic Won/Sent/Estimated window. Projection uses the REAL CT today, so its
// rows are seeded relative to now() (the same anchor the band CASE uses).
const NOW = new Date("2026-05-27T18:00:00Z");
let FROM = "";
let TO = "";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let tdb: any;
let pg: PGlite;

function execRows(q: SQL): Promise<Array<Record<string, unknown>>> {
  return tdb.execute(q).then((r: unknown) => {
    if (Array.isArray(r)) return r as Array<Record<string, unknown>>;
    return ((r as { rows?: Array<Record<string, unknown>> })?.rows ?? []) as Array<Record<string, unknown>>;
  });
}
const n = (v: unknown) => Number(v ?? 0);
const sumVal = (rows: Array<Record<string, unknown>>) => rows.reduce((s, r) => s + n(r.value), 0);

beforeAll(async () => {
  const period = getWtdPeriod("to_date", NOW);
  FROM = period.from;
  TO = period.to;

  pg = new PGlite();
  await pg.exec(`
    CREATE TABLE users (id uuid PRIMARY KEY, display_name text NOT NULL);
    CREATE TABLE pipeline_stage_config (
      id uuid PRIMARY KEY, name text NOT NULL, slug text UNIQUE NOT NULL,
      workflow_family text NOT NULL DEFAULT 'standard_deal', is_terminal boolean NOT NULL DEFAULT false
    );
    CREATE TABLE deals (
      id uuid PRIMARY KEY, sales_source_user_id uuid, deal_number text, project_number text, name text NOT NULL, stage_id uuid NOT NULL,
      assigned_rep_id uuid, is_test_data boolean NOT NULL DEFAULT false, on_hold boolean NOT NULL DEFAULT false,
      is_active boolean NOT NULL DEFAULT true, won_closed_date date, expected_close_date date, bid_due_date timestamptz,
      dd_estimate numeric, bid_estimate numeric, awarded_amount numeric, bid_board_total_sales numeric,
      company_id uuid, region_id uuid, project_type text, project_type_id uuid, stage_entered_at timestamptz,
      win_probability integer
    );
    CREATE TABLE deal_stage_history (
      id uuid PRIMARY KEY DEFAULT gen_random_uuid(), deal_id uuid NOT NULL, to_stage_id uuid NOT NULL,
      created_at timestamptz NOT NULL
    );
    CREATE TABLE leads (
      id uuid PRIMARY KEY, name text NOT NULL, stage_id uuid NOT NULL, assigned_rep_id uuid,
      status text NOT NULL DEFAULT 'open', is_active boolean NOT NULL DEFAULT true,
      is_test_data boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(),
      company_id uuid, project_type text, project_type_id uuid, stage_entered_at timestamptz
    );
    -- Additive enrichment joins for the drill-down (company/region/type). Empty here: LEFT JOINs return
    -- NULL, proving the new columns DON'T change the reconciling cohort (counts/$ below are unaffected).
    CREATE TABLE companies (id uuid PRIMARY KEY, name text NOT NULL, region text);
    CREATE TABLE region_config (id uuid PRIMARY KEY, name text NOT NULL);
    CREATE TABLE project_type_config (id uuid PRIMARY KEY, name text NOT NULL);

    INSERT INTO users (id, display_name) VALUES
      ('${REP_A}', 'Alice Rep'), ('${REP_B}', 'Bob Rep');

    INSERT INTO pipeline_stage_config (id, name, slug, workflow_family, is_terminal) VALUES
      ('${ST.won}',        'Won',          '${WON_STAGE_SLUGS[0]}',    'standard_deal', true),
      ('${ST.open}',       'Opportunity',  'opportunity',              'standard_deal', false),
      ('${ST.sent}',       'Estimate Sent','${SENT_STAGE_SLUGS[0]}',   'standard_deal', false),
      ('${ST.estimating}', 'Estimating',   '${ESTIMATED_STAGE_SLUGS[0]}','standard_deal', false),
      ('${ST.leadNew}',    'New',          'lead_new',                 'lead', false),
      ('${ST.leadContacted}','Contacted',  'lead_contacted',           'lead', false);

    -- ===== WON: close-date cohort. In-window non-test non-hold deals count; others excluded. =====
    INSERT INTO deals (id, deal_number, project_number, name, stage_id, assigned_rep_id, won_closed_date, awarded_amount, is_test_data, on_hold) VALUES
      ('${D.w1}','HS-318651319000','DFW-1-09026-af','Won A1','${ST.won}','${REP_A}','2026-05-25', 100000, false, false),
      ('${D.w2}','W-2',NULL,'Won B1','${ST.won}','${REP_B}','2026-05-26', 200000, false, false),
      ('${D.w3}','W-3',NULL,'Won unassigned','${ST.won}',NULL,'2026-05-25', 50000, false, false),
      ('${D.w4}','W-4',NULL,'Won onhold (excl)','${ST.won}','${REP_A}','2026-05-25', 999, false, true),
      ('${D.w5}','W-5',NULL,'Won test (excl)','${ST.won}','${REP_A}','2026-05-25', 888, true, false),
      ('${D.w6}','W-6',NULL,'Won out-of-window (excl)','${ST.won}','${REP_A}','2026-05-20', 777, false, false);

    -- ===== SENT / ESTIMATED: stage-entry cohort on deal_stage_history within the CT window. =====
    INSERT INTO deals (id, deal_number, name, stage_id, assigned_rep_id, bid_board_total_sales, on_hold, is_test_data) VALUES
      ('${D.s1}','S-1','Sent A','${ST.open}','${REP_A}', 30000, false, false),
      ('${D.s2}','S-2','Sent B','${ST.open}','${REP_B}', 45000, false, false),
      ('${D.s3}','S-3','Sent out','${ST.open}','${REP_A}', 11111, false, false),
      ('${D.s4}','S-4','Sent onhold','${ST.open}','${REP_A}', 22222, true, false),
      ('${D.e1}','E-1','Est A','${ST.open}','${REP_A}', 60000, false, false),
      ('${D.e2}','E-2','Est B','${ST.open}','${REP_B}', 70000, false, false);
    INSERT INTO deal_stage_history (deal_id, to_stage_id, created_at) VALUES
      ('${D.s1}','${ST.sent}','2026-05-25T15:00:00Z'),
      ('${D.s1}','${ST.sent}','2026-05-26T15:00:00Z'),
      ('${D.s2}','${ST.sent}','2026-05-26T16:00:00Z'),
      ('${D.s3}','${ST.sent}','2026-05-20T16:00:00Z'),
      ('${D.s4}','${ST.sent}','2026-05-25T16:00:00Z'),
      ('${D.e1}','${ST.estimating}','2026-05-25T17:00:00Z'),
      ('${D.e2}','${ST.estimating}','2026-05-26T17:00:00Z');

    -- ===== PROJECTION: open, future-dated relative to CT today (same anchor as the band CASE). =====
    INSERT INTO deals (id, deal_number, name, stage_id, assigned_rep_id, expected_close_date, bid_board_total_sales, is_active, on_hold, is_test_data) VALUES
      ('${D.p1}','P-1','Proj A 0_30','${ST.open}','${REP_A}', (now() AT TIME ZONE 'America/Chicago')::date + 10, 30000, true, false, false),
      ('${D.p2}','P-2','Proj A 31_60','${ST.open}','${REP_A}', (now() AT TIME ZONE 'America/Chicago')::date + 45, 40000, true, false, false),
      ('${D.p3}','P-3','Proj B 0_30','${ST.open}','${REP_B}', (now() AT TIME ZONE 'America/Chicago')::date + 20, 20000, true, false, false),
      ('${D.p4}','P-4','Proj A null (M only)','${ST.open}','${REP_A}', NULL, 15000, true, false, false),
      ('${D.p5}','P-5','Proj A past (excl)','${ST.open}','${REP_A}', (now() AT TIME ZONE 'America/Chicago')::date - 5, 12000, true, false, false),
      ('${D.p6}','P-6','Proj onhold (excl)','${ST.open}','${REP_A}', (now() AT TIME ZONE 'America/Chicago')::date + 10, 13000, true, true, false);

    -- ===== LEADS: active open leads per stage/rep. Closed/inactive/test excluded. =====
    INSERT INTO leads (id, name, stage_id, assigned_rep_id, status, is_active, is_test_data) VALUES
      ('${D.l1}','Lead A new','${ST.leadNew}','${REP_A}','open', true, false),
      ('${D.l2}','Lead B new','${ST.leadNew}','${REP_B}','open', true, false),
      ('${D.l3}','Lead A contacted','${ST.leadContacted}','${REP_A}','open', true, false),
      ('${D.l4}','Lead closed (excl)','${ST.leadNew}','${REP_A}','won', true, false),
      ('${D.l5}','Lead inactive (excl)','${ST.leadNew}','${REP_A}','open', false, false),
      ('${D.l6}','Lead test (excl)','${ST.leadNew}','${REP_A}','open', true, true);
  `);

  tdb = drizzle(pg);
});

afterAll(async () => {
  await pg?.close?.();
});

describe("Won evidence reconciles to the protected getWonCloseSummary", () => {
  it("office Won: evidence rows === count, sum(value) === $", async () => {
    const agg = await getWonCloseSummary(tdb, { from: FROM, to: TO });
    const rows = await execRows(buildWonEvidenceSql(FROM, TO));
    expect(agg.count).toBe(3); // meaningful, non-trivial
    expect(rows.length).toBe(agg.count);
    expect(sumVal(rows)).toBeCloseTo(agg.totalValue, 2);
    const nums = rows.map((r) => r.deal_number);
    expect(nums).not.toContain("W-4"); // on-hold
    expect(nums).not.toContain("W-5"); // test
    expect(nums).not.toContain("W-6"); // out of window
    // the new project_number column surfaces in the row payload: the canonical DFW number rides alongside
    // the raw HubSpot deal_number, so the client resolver can show the DFW number and hide the HS id
    const w1 = rows.find((r) => r.project_number === "DFW-1-09026-af");
    expect(w1).toBeTruthy();
    expect(w1?.deal_number).toBe("HS-318651319000");
  });

  it("per-rep Won: each rep's evidence === getCanonicalRepWonSummary row, and per-rep sums to office", async () => {
    const repRows = await getCanonicalRepWonSummary(tdb, { from: FROM, to: TO });
    expect(repRows.length).toBeGreaterThan(0);
    for (const rr of repRows) {
      const rows = await execRows(buildWonEvidenceSql(FROM, TO, rr.repId));
      expect(rows.length).toBe(rr.winsCount);
      expect(sumVal(rows)).toBeCloseTo(rr.closedValue, 2);
    }
    const office = await execRows(buildWonEvidenceSql(FROM, TO));
    const repSum = (await Promise.all(repRows.map((rr) => execRows(buildWonEvidenceSql(FROM, TO, rr.repId)))))
      .reduce((s, rows) => s + rows.length, 0);
    expect(repSum).toBe(office.length);
  });
});

async function aggregateCohort(slugs: readonly string[]): Promise<{ count: number; value: number; byRep: Map<string | null, { count: number; value: number }> }> {
  const rows = await execRows(buildStageEntryCohortSql(slugs, FROM, TO));
  const byRep = new Map<string | null, { count: number; value: number }>();
  let count = 0;
  let value = 0;
  for (const r of rows) {
    const repId = (r.rep_id as string | null) ?? null;
    const c = n(r.cnt);
    const v = n(r.val);
    byRep.set(repId, { count: c, value: v });
    count += c;
    value += v;
  }
  return { count, value, byRep };
}

describe.each([
  ["sent", SENT_STAGE_SLUGS],
  ["estimated", ESTIMATED_STAGE_SLUGS],
] as const)("%s evidence reconciles to its stage-entry cohort aggregate", (_label, slugs) => {
  it("office + per-rep counts and $ match", async () => {
    const agg = await aggregateCohort(slugs);
    expect(agg.count).toBeGreaterThan(0);

    const officeRows = await execRows(buildStageEntryEvidenceSql(slugs, FROM, TO));
    expect(officeRows.length).toBe(agg.count);
    expect(sumVal(officeRows)).toBeCloseTo(agg.value, 2);

    for (const [repId, totals] of agg.byRep) {
      const rows = await execRows(buildStageEntryEvidenceSql(slugs, FROM, TO, repId));
      expect(rows.length).toBe(totals.count);
      expect(sumVal(rows)).toBeCloseTo(totals.value, 2);
    }
  });
});

describe("Projection evidence reconciles to the bands aggregate (per band, per rep)", () => {
  const BANDS: ProjectionBand[] = ["0_30", "31_60", "61_90", "beyond_90"];

  it("each band's evidence === that rung's aggregate count/$", async () => {
    const aggRows = await execRows(buildProjectionBandsSql());
    const officeByBand = new Map<string, { count: number; value: number }>();
    const repByBand = new Map<string, { count: number; value: number }>();
    for (const r of aggRows) {
      const band = String(r.band);
      const repId = (r.rep_id as string | null) ?? null;
      const cur = officeByBand.get(band) ?? { count: 0, value: 0 };
      officeByBand.set(band, { count: cur.count + n(r.cnt), value: cur.value + n(r.val) });
      repByBand.set(`${repId}|${band}`, { count: n(r.cnt), value: n(r.val) });
    }
    const totalProjected = [...officeByBand.values()].reduce((s, b) => s + b.count, 0);
    expect(totalProjected).toBeGreaterThan(0);

    for (const band of BANDS) {
      const expected = officeByBand.get(band) ?? { count: 0, value: 0 };
      const rows = await execRows(buildProjectionEvidenceSql(undefined, band));
      expect(rows.length).toBe(expected.count);
      expect(sumVal(rows)).toBeCloseTo(expected.value, 2);
    }

    for (const [key, expected] of repByBand) {
      const [repId, band] = key.split("|");
      const rows = await execRows(buildProjectionEvidenceSql(repId === "null" ? null : repId, band as ProjectionBand));
      expect(rows.length).toBe(expected.count);
    }
  });

  it("excluded deals (past-dated, on-hold, null-dated) never appear in any band", async () => {
    const all = (await Promise.all(BANDS.map((b) => execRows(buildProjectionEvidenceSql(undefined, b))))).flat();
    const numbers = all.map((r) => r.deal_number);
    expect(numbers).not.toContain("P-5"); // past-dated
    expect(numbers).not.toContain("P-6"); // on-hold
    expect(numbers).not.toContain("P-4"); // null-dated (M only, not a band)
  });
});

describe("Undated evidence reconciles to the projection coverage complement (M − N)", () => {
  it("office: COUNT(undated) === M − N === M − Σ band counts, and SUM($) === coverage.undated_value", async () => {
    // M / N (and the undated $) over the SAME open scope buildProjectionCoverageSql counts.
    const covRows = await execRows(buildProjectionCoverageSql());
    const officeM = covRows.reduce((s, r) => s + n(r.m), 0);
    const officeN = covRows.reduce((s, r) => s + n(r.n), 0);
    const officeUndatedValue = covRows.reduce((s, r) => s + n(r.undated_value), 0);

    // Σ band counts == the future-dated N (the four dated bands), surfaced by the bands aggregate.
    const bandRows = await execRows(buildProjectionBandsSql());
    const sumBandCounts = bandRows.reduce((s, r) => s + n(r.cnt), 0);

    const undated = await execRows(buildUndatedEvidenceSql());

    // The FULL complement: ALL open deals lacking a future-dated close date — not just the projection
    // deals, but every open deal whose expected_close_date is null/stale (the sent/estimated deals carry
    // no close date, so they sit here too). Non-trivial: > the dated bands, and reconciles three ways.
    expect(officeM - officeN).toBeGreaterThan(0);
    expect(sumBandCounts).toBe(officeN); // bands carry ONLY future-dated deals (Σ bands == N)
    expect(undated.length).toBe(officeM - officeN); // COUNT(undated) == M − N
    expect(undated.length).toBe(officeM - sumBandCounts); // == M − Σ band counts
    expect(undated.length).toBeGreaterThan(sumBandCounts); // the blind spot is the larger slice here
    // the undated card's $ === SUM($) of exactly these rows (buildProjectionCoverageSql's FILTERed sum)
    expect(sumVal(undated)).toBeCloseTo(officeUndatedValue, 2);
    expect(officeUndatedValue).toBeGreaterThan(0);

    // includes both blind-spot kinds (never-dated P-4 + stale-past-dated P-5) AND the no-close-date open
    // deals (a sent/estimated deal); future-dated bands + the on-hold deal are absent.
    const numbers = undated.map((r) => r.deal_number);
    expect(numbers).toContain("P-4"); // null-dated (no_date)
    expect(numbers).toContain("P-5"); // stale past-dated (stale_dated)
    expect(numbers).toContain("S-1"); // an open (sent) deal with no close date — full complement
    expect(numbers).not.toContain("P-1"); // future-dated (a band)
    expect(numbers).not.toContain("P-2");
    expect(numbers).not.toContain("P-3");
    expect(numbers).not.toContain("P-6"); // on-hold → not reportable, never in M
    expect(numbers).not.toContain("S-4"); // on-hold sent deal → not in M either
  });

  it("per-rep undated === that rep's M − N, and the per-rep slices sum to the office set", async () => {
    const covRows = await execRows(buildProjectionCoverageSql());
    let perRepSum = 0;
    for (const r of covRows) {
      const repId = (r.rep_id as string | null) ?? null;
      const rows = await execRows(buildUndatedEvidenceSql(repId));
      expect(rows.length).toBe(n(r.m) - n(r.n));
      perRepSum += rows.length;
    }
    const office = await execRows(buildUndatedEvidenceSql());
    expect(perRepSum).toBe(office.length);
  });
});

describe("Lead evidence reconciles to buildLeadStatusSql (per rep + stage)", () => {
  it("each rep/stage lead count === aggregate, excluded leads absent", async () => {
    const aggRows = await execRows(buildLeadStatusSql());
    expect(aggRows.length).toBeGreaterThan(0);
    for (const r of aggRows) {
      const repId = (r.rep_id as string | null) ?? null;
      const stageLabel = String(r.stage_label);
      const rows = await execRows(buildLeadEvidenceSql(repId, stageLabel));
      expect(rows.length).toBe(n(r.cnt));
      expect(rows.every((row) => row.value == null)).toBe(true); // leads carry no $
    }
    const office = await execRows(buildLeadEvidenceSql());
    const names = office.map((r) => r.name);
    expect(names).not.toContain("Lead closed (excl)");
    expect(names).not.toContain("Lead inactive (excl)");
    expect(names).not.toContain("Lead test (excl)");
  });
});
